config/routes.rb
# -*- encoding : utf-8 -*-
RedmineApp::Application.routes.draw do
  match '/spent_time/update_project_issues', to: 'spent_time#update_project_issues', as: 'update_project_issues_spent_time', :via => [:post]
  match '/spent_time/create_entry', to: 'spent_time#create_entry', as: 'create_entry_spent_time', :via => [:post]
  #match '/spent_time/update_entry', to: 'spent_time#update_entry', as: 'update_entry_spent_time', :via => [:put]
  get '/spent_time/destroy_entry', to: 'spent_time#destroy_entry', as: 'destroy_entry_spent_time'
  match '/spent_time/report', to: 'spent_time#report', as: 'report_spent_time', :via => [:get, :post]
  match '/spent_time', to: 'spent_time#index', as: 'index_spent_time', :via => [:get, :post]
end

app/controllers/spent_time_controller.rb
class SpentTimeController < ApplicationController

  helper :timelog
  include TimelogHelper
  helper :spent_time
  include SpentTimeHelper
  helper :custom_fields
  include CustomFieldsHelper

  # Show the initial form.
  # * If user has permissions to see spent time for every project
  # the users combobox is filled with all the users.
  # * If user has permissions to see other members' spent times of the projects he works in,
  # the users combobox is filled with their co-workers
  # * If the user only has permissions to see his own report, the users' combobox is filled with the user himself.
  def index
    @user = User.current
    @users = []
    if authorized_for?(:view_every_project_spent_time)
      @users = User.active.order(:firstname)
    elsif authorized_for?(:view_others_spent_time)
      projects = User.current.projects
      projects.each { |project| @users.concat(project.users) }
      @users.uniq!
      @users.order(:firstname)
    else
      @users = [@user]
    end
    params[:period] ||= '7_days'
    make_time_entry_report(nil, nil, User.current)
    @assigned_issues = []
    @same_user = true
    @time_entry = TimeEntry.new
  end

  # Show the report of spent time between two dates for an user
  def report
    @user = User.current
    projects = nil
    if authorized_for?(:view_every_project_spent_time)
      projects = Project.find(:all)
    elsif authorized_for?(:view_others_spent_time)
      projects = User.current.projects
    end
    make_time_entry_report(params[:from], params[:to], params[:user], projects)
    another_user = User.find(params[:user])
    @same_user = (@user.id == another_user.id)
    respond_to do |format|
      format.js
    end
  end

  # Delete a time entry
  def destroy_entry
    @time_entry = TimeEntry.find(params[:id])
    render_404 and return unless @time_entry
    render_403 and return unless @time_entry.editable_by?(User.current)
    @time_entry.destroy

    @user = User.current
    @from = params[:from].to_s.to_date
    @to = params[:to].to_s.to_date
    make_time_entry_report(params[:from], params[:to], @user)
    respond_to do |format|
      format.js
    end
  rescue ::ActionController::RedirectBackError
    redirect_to :action => 'index'
  end
  
  # Create a new time entry
  def create_entry
    @user = User.current
    raise t('project_is_mandatory_error') if params[:project_id].to_i < 0

    begin
      @time_entry_date = params[:time_entry_spent_on].to_s.to_date
    rescue
      raise 'invalid_date_error'
    end

    raise 'invalid_hours_error' unless is_numeric?(params[:time_entry][:hours].to_f)
    params[:time_entry][:spent_on] = @time_entry_date
    @from = params[:from].to_s.to_date
    @to = params[:to].to_s.to_date

    # Save the new record
    @time_entry = TimeEntry.new(:user => @user)
    @time_entry.attributes = params[:time_entry]

    begin
      @project = Project.find(params[:project_id])

      unless allowed_project?(params[:project_id])
        raise t('not_allowed_error', :project => @project)
      end
    rescue ActiveRecord::RecordNotFound
      raise t('cannot_find_project_error', project_id=>params[:project_id])
    end

    @time_entry.project = @project
    issue_id = (params[:issue_id] == nil) ? 0 : params[:issue_id].to_i
    if issue_id > 0
      begin
        @issue = Issue.find(issue_id)
      rescue ActiveRecord::RecordNotFound
        raise t('issue_not_found_error', :issue_id=> issue_id)
      end

      if @project.id==@issue.project_id
        @time_entry.issue = @issue
      else
        raise t('issue_not_in_project_error', issue=>@issue, project=>@project)
      end
    end

    render_403 and return if @time_entry && !@time_entry.editable_by?(@user)
    @time_entry.user = @user
    if @time_entry.save!
      flash[:notice] = l('time_entry_added_notice')
      respond_to do |format|
        if @time_entry_date > @to
          @to = @time_entry_date
        elsif @time_entry_date < @from
          @from = @time_entry_date
        end
        make_time_entry_report(@from, @to, @user)
        format.js
      end
    end
    rescue Exception => ex
      respond_to do |format|
        flash[:error] = ex.message
        format.js { render 'spent_time/create_entry_error'}
      end
  end

  # Update the project's issues when another project is selected
  def update_project_issues
    @to = params[:to].to_date
    @from = params[:from].to_date
    project = Project.find(params[:project_id])
    @time_entry = TimeEntry.new(:project => project)
    find_assigned_issues_by_project(params[:project_id])
    respond_to do |format|
      format.js
    end
  end

  private
  
  def is_numeric?(obj) 
   obj.to_s.match(/\A[+-]?\d+?(\.\d+)?\Z/) == nil ? false : true
  end

  def allowed_project?(project_id)
    project = Project.find(project_id)
    allowed = project.allows_to?(:log_time)
    allowed ? project : nil
  end

end

app/helpers/spent_time_helper.rb
module SpentTimeHelper
  def authorized_for?(action)
    User.current.allowed_to?(action, nil, { :global => :true })
  end

  # Find issues assigned to the user and issues not assigned to him which the user has spent time
  def find_assigned_issues_by_project(project)
    @user = User.current
    begin
      @project = Project.find(project)
    rescue
      @assigned_issues = []
    else
      conditions = []
      conditions << "(#{Issue.table_name}.assigned_to_id=:user_id or #{TimeEntry.table_name}.user_id=:user_id)"
      conditions << "#{IssueStatus.table_name}.is_closed=false"
      conditions << "#{Project.table_name}.status=#{Project::STATUS_ACTIVE}"
      conditions << "#{Project.table_name}.id=:project_id"
      arguments = {:user_id => @user.id, :project_id => @project.id}
      @assigned_issues = Issue.joins(:status, :project, :tracker, :priority)
                              .joins('LEFT JOIN time_entries ON time_entries.issue_id = issues.id')
                             .where(conditions.join(' AND '), arguments)
                              .distinct
                             .order("#{Issue.table_name}.id DESC, #{Issue.table_name}.updated_on DESC")
    end
    @assigned_issues
  end

  # Returns the list of type of activities ordered by name
  def activities_for_select
      collection = activity_collection_for_select_options
      # Gets & removes the first element (--Please select)
      first = collection.shift
      ordered_collection = []
      # Add 'select' label
      ordered_collection << first
      # Order the rest of elements & add them to the collection
      ordered_collection.concat(collection.sort { |a, b| a <=> b })
      ordered_collection
  end
  
  # Render select project as tree
  def render_project_tree    
      select_tag('project_id', "<option value='-1'>-#{l(:select_project_option)}</option>".html_safe +
                           project_tree_options_for_select(user_projects_ordered),
                           {:onchange => "$.post('#{update_project_issues_spent_time_path(:from => @from, :to => @to)}', {'_method':'post', 'project_id':this.value});".html_safe})    
  end

  # Returns the users' projects ordered by name
  def user_projects_ordered
      projects = @user.projects.active.sort {|a,b| a.name <=> b.name}
      find_assigned_issues_by_project(projects.first) if (projects.length == 1)
      projects
  end

  # Make the spent time report between two dates for a given user
  # Params:
  # +from+:: First date to search for time entries
  # +to+:: Last date to search for time entries
  # +user+:: User for whom the report is being done
  # +projects+:: Array of projects involved in the query. If nil then all projects
  def make_time_entry_report(from, to, user, projects = nil)
    conditions = []
    arguments = {}

    conditions << "#{TimeEntry.table_name}.spent_on BETWEEN :from AND :to"
    figure_out_date_range(from, to)
    arguments[:from] = @from
    arguments[:to] = @to

    if User.exists?(user)
      # Used in the view
      query_user = User.find(user)
      conditions << "#{TimeEntry.table_name}.user_id = :user"
      arguments[:user] = user
    end

    if projects
      conditions << "#{TimeEntry.table_name}.project_id in (:projects)"
      arguments[:projects] = projects.map { |c| c.id }
    end

    @entries = TimeEntry.where(
            conditions.join(' AND '), arguments,
            :include => [:activity, :project, {:issue => [:tracker, :status]}],
            :order => "#{TimeEntry.table_name}.spent_on DESC, #{Project.table_name}.name ASC, #{Tracker.table_name}.position ASC, #{Issue.table_name}.id ASC")
    @entries_by_date = @entries.group_by(&:spent_on)
    @total_estimated_time = 0
    @entries.group_by(&:issue).each_key {|issue| 
        if issue
            @total_estimated_time += (issue.estimated_hours ? issue.estimated_hours.to_f : 0)
        end
    }
    @assigned_issues = []
    @activities = TimeEntryActivity.all
  end

  # Retrieves the date range based on predefined ranges or specific from/to param dates
  def figure_out_date_range(from, to)
    @free_period = false
    @from, @to = nil, nil

    if params[:period_type] == '1' || (params[:period_type].nil? && !params[:period].nil?)
      case params[:period].to_s
      when 'today'
        @from = @to = Date.today
      when 'yesterday'
        @from = @to = Date.today - 1
      when 'current_week'
        @from = Date.today - (Date.today.cwday - 1)%7
        @to = @from + 6
      when 'last_week'
        @from = Date.today - 7 - (Date.today.cwday - 1)%7
        @to = @from + 6
      when 'last_2_weeks'
        @from = Date.today - 14 - (Date.today.cwday - 1)%7
        @to = @from + 13      
      when '7_days'
        @from = Date.today - 7
        @to = Date.today
      when 'current_month'
        @from = Date.civil(Date.today.year, Date.today.month, 1)
        @to = (@from >> 1) - 1
      when 'last_month'
        @from = Date.civil(Date.today.year, Date.today.month, 1) << 1
        @to = (@from >> 1) - 1
      when '30_days'
        @from = Date.today - 30
        @to = Date.today
      when 'current_year'
        @from = Date.civil(Date.today.year, 1, 1)
        @to = Date.civil(Date.today.year, 12, 31)
      end
    elsif params[:period_type] == '2' || (params[:period_type].nil? && (!from.nil? || !to.nil?))
      begin; @from = from.to_s.to_date unless from.blank?; rescue; end
      begin; @to = to.to_s.to_date unless to.blank?; rescue; end
      @free_period = true
    else
      # default
    end

    @from, @to = @to, @from if @from && @to && @from > @to
    @from ||= (TimeEntry.minimum(:spent_on, :include => :project, :conditions => Project.allowed_to_condition(User.current, :view_time_entries)) || Date.today) - 1
    @to   ||= Date.today
  end

  def get_activities(entry)
    activities = []
    entry.project.activities.each {|a| activities << [a.id, a.name]}
    activities
  end

  def options_for_period_select(value)
    options_for_select([[l(:label_all_time), 'all'],
                        [l(:label_today), 'today'],
                        [l(:label_yesterday), 'yesterday'],
                        [l(:label_this_week), 'current_week'],
                        [l(:label_last_week), 'last_week'],
                        [l(:label_last_n_weeks, 2), 'last_2_weeks'],
                        [l(:label_last_n_days, 7), '7_days'],
                        [l(:label_this_month), 'current_month'],
                        [l(:label_last_month), 'last_month'],
                        [l(:label_last_n_days, 30), '30_days'],
                        [l(:label_this_year), 'current_year']],
                       value)
  end
end

app/views/spent_time/_bulk_insert.html.erb
<div id='new_entries_form'  style='display:none;'>
  <%= form_tag(:url => {:action => :dates_for_create_entries}, :remote => true, :update => 'new_entries_dates') do %>
    <p>
      <%= l(:label_issue) %>
    </p>
    <p>
      <%= l(:label_date_from) %>
      <%= text_field_tag('init_date', '', :size => 10) %> <%= calendar_for('init_date') %>
      <%= l(:label_date_to) %>
      <%= text_field_tag('end_date', '', :size => 10) %> <%= calendar_for('end_date') %>
      <%= submit_tag l(:button_apply), :name => nil %>
    </p>
  <% end %>
  <div id="new_entries_dates">
    <%= form_tag(:url => {:action => :create_entries}, :remote => true) do %>
    <% end %>
  </div>
</div>

app/views/spent_time/_new_entries.html.erb
<%= form_tag(:url => {:action => :create_entries}, :remote => true) do %>
  <p>
    <%= l(:label_issue) %>
    <%= select_tag 'issue', options_for_select(@assigned_issues.collect {|issue| ["##{issue.id} - #{issue.subject}", issue.id]}) %>
  </p>
  <p>
    <%= l(:label_date_from) %>
    <%= text_field_tag('init_date', '', :size => 10) %> <%= calendar_for('init_date') %>
    <%= l(:label_date_to) %>
    <%= text_field_tag('end_date', '', :size => 10) %> <%= calendar_for('end_date') %>
  </p>
<% end %>

app/views/spent_time/_new_time_entry_form.html.erb
<div id='new_time_entry_form' <%= "style='display:none'" unless @same_user %>>
  <fieldset>
    <legend><%= l(:label_new_entry) %></legend>
    <%= form_tag(create_entry_spent_time_path(:from => @from, :to => @to), :id => "form_new_entry", :remote => true) do -%>
      <p>
        <%= l(:label_project) %>
        <% if user_projects_ordered.length == 1
           then %>
            <%= select_tag('project_id', "<option value='#{user_projects_ordered.first.id}' selected>#{user_projects_ordered.first.name}</option>".html_safe)%>
        <% else %>
        	<%= render_project_tree %>                                                     
        <% end %>
      </p>
      <p>
        <%= render :partial => 'fields_for_new_entry_form' %>
      </p>
    <% end -%>
  </fieldset>
</div>

app/views/spent_time/_report_menu_options.html.erb
<div id="report_menu_options" style='display:none;'>
  <%= link_to_function(l(:label_add_entry), "$('#new_time_entry_form').toggle();$('#report_menu_options').toggle();".html_safe) if @same_user %>
</div>

app/views/spent_time/_time_entries_by_date.html.erb
<% is_weekend = (day.wday == 0 || day.wday == 6) %>
<tr id='"time_entry.#{day}"' class="odd <%= (is_weekend ? 'weekend_row' : '')%>">
  <td class="centered"><strong><%= day == Date.today ? l(:label_today).titleize : format_date(day) %></strong></td>
  <% if is_weekend %>
    <td colspan="2" class="centered"><%= l(:weekend) %> </td>
  <% else %>
    <td colspan="2"></td>
  <% end %>
  <%
    total_hours = (@entries_by_date[day].nil? ? 0 : @entries_by_date[day].sum(&:hours).to_f)
    style = 'hours'
    if total_hours < 8.0
        style = 'less_than_8_hours'
    elsif total_hours > 8.0
        style = 'more_than_8_hours'
    end
  %>
  <td class="<%= style %> centered"><em><%= '%.2f' % total_hours %></em></td>
  <td class="<%= 'hours' %> centered"><em>--</em></td>
  <td class="<%= 'hours' %> centered"><em>--</em></td>
  <td></td>
</tr>
<% unless @entries_by_date[day].nil? %>
  <% @entries_by_date[day].each do |entry| %>
    <%= render :partial => 'time_entry_row', :locals => {:entry => entry} %>
  <% end %>
<% end %>

app/views/spent_time/_time_entry_row.html.erb
<tr id='<%= "time_entry.#{entry.id}" %>' class="time-entry" style="border-bottom: 1px solid #f5f5f5;">
  <td class="activity centered"><%=h entry.activity.name %></td>
  <td class="subject"><%=h entry.project %> - [<%=raw( entry.issue ? entry.issue.status : l(:issue_not_exists))%>] <%= raw (' - ' + link_to_issue(entry.issue)) if entry.issue %></td>
  <td class="comments"><%= truncate(entry.comments, length: 150) %></td>
  <td class="issue-hours centered"><%= h entry.hours ? '%.2f' % entry.hours : '0.00' %></td>
  <td class="issue-hours centered"><%= h entry.issue ? entry.issue.estimated_hours : '0.00' %></td>
  <td class="issue-hours centered"><%= h entry.issue ? '%.2f' % entry.issue.total_spent_hours : '0.00' %></td>
  <td class="centered">
  <% if entry.editable_by?(@user) %>
      <%= link_to(image_tag('edit.png'), {:controller => 'timelog', :action => 'edit', :id => entry},
                  :title => l(:button_edit)) %>
      <%= link_to(image_tag('delete.png'), {:controller => 'spent_time', :action => 'destroy_entry', :id => entry.id, :from => @from, :to => @to}, 
                  :remote => true,
                  :data => {:confirm => l(:text_are_you_sure)}) %>
  <% end %>
  </td>
</tr>

app/views/spent_time/create_entry.js.erb
var flashNotice = $("#flash_notice");
flashNotice.remove();
$("#flash_error").remove();
$("#content").prepend("<div class='flash notice' id='flash_notice'><%=flash[:notice]%></div>");
$('#time_entries_report').html("<%= escape_javascript(render :partial => 'time_entries_report') %>");
flashNotice.fadeOut(3000);

app/views/spent_time/create_new_date_entry.js.erb
$('time_entry.' + <%= @previous_time_entry.id %>).append(render(:partial => 'time_entry_row', :locals => {:entry => @time_entry}))
$('time_entry.' + <%= @time_entry.id %>).effect("highlight", {color:'#92A6FF'}, 3000)

app/views/spent_time/dates_for_bulk_insert.html.erb
<%= form_tag(:url => {:action => :create_entries}, :update => 'report', :remote => true) do %>
    <%= hidden_field_tag('issue', @issue.id) %>
    <%= hidden_field_tag('init_date', @init_date) %>
    <%= hidden_field_tag('end_date', @end_date) %>
  <table class="list time-entries">
    <thead>
      <th><%= l(:label_date) %></th>
      <th><%= l(:label_activity) %></th>
      <th><%= l(:field_hours) %></th>
      <th><%= l(:field_comments) %></th>
    </thead>
    <tbody>
    <% i = 0
       @init_date.upto(@end_date) do |date|
         # Si no es un sábado o un domingo...
         unless [0,6].include?(date.wday)
           prefix = "time_log#{i.to_s}."
           i += 1 %>
           <tr>
             <td><%= date%></td>
             <%= hidden_field_tag(prefix + 'date', date) %>
             <td><%= select_tag(prefix + 'activity', options_for_select(@activities))%> </td>
             <td><%= text_field_tag(prefix + 'hours', '', :size => 6)%> </td>
             <td><%= text_field_tag(prefix + 'comment', '', :size => 100)%> </td>
           </tr>
        <% end %>
    <% end -%>
    </tbody>
  </table>
  <%= hidden_field_tag('number_of_dates', i - 1) %>
  <%= submit_tag l(:button_apply), :name => nil %>
<% end -%>

app/views/spent_time/destroy_entry.js.erb
$('#time_entries_report').html("<%= escape_javascript(render :partial => 'time_entries_report')%>");

app/views/spent_time/index.html.erb
<% content_for :header_tags do %>
    <%= stylesheet_link_tag 'spent_time', :plugin => 'redmine_spent_time' %>
<% end %>

<%= form_tag(report_spent_time_path, :id => "form_query", :remote => true,
             :onsubmit => "new Ajax.Request('#{report_spent_time_path}', {asynchronous:true, evalScripts:true, method:'get', parameters:Form.serialize(this)}); return false;") do -%>
  <h2><%=l(:label_spent_time) %></h2>
  <fieldset id="filters"><legend><%= l(:label_interval) %></legend>
    <p>
      <%= l(:label_person) %>
      <%= select_tag(:user, options_from_collection_for_select(@users, 'id', 'name', @user.id))%>
      <%= radio_button_tag('period_type', '1', !@free_period) %>
      <%= select_tag('period', options_for_period_select(params[:period]),
                               :onchange => "$('form_query').onsubmit();".html_safe,
                               :onfocus => "$user_projects_ordered('period_type_1').checked = true;".html_safe) %>
      <%= radio_button_tag('period_type', '2', @free_period) %>
      <span onclick="$('period_type_2').checked = true;">
        <%= l(:label_date_from) %>
        <%= text_field_tag('from', @from, :size => 10) %> <%= calendar_for('from') %>
        <%= l(:label_date_to) %>
        <%= text_field_tag('to', @to, :size => 10) %> <%= calendar_for('to') %>
      </span>
      <%= submit_tag l(:button_apply), :name => nil, :id => "submit_report" %>
    </p>
  </fieldset>
<% end %>
<div id='report'>
  <!-- Here goes the report's result -->
   <%= render :partial => 'new_time_entry_form' %>
   <%= render :partial => 'report_menu_options' %>
   <%= render :partial => 'time_entries_report' %>
</div>

app/views/spent_time/report.js.erb
var report = $('#report');
report.html("<%= escape_javascript(render :partial => 'new_time_entry_form') %>");
report.append("<%= escape_javascript(render :partial => 'report_menu_options') %>");
report.append("<%= escape_javascript(render :partial => 'time_entries_report') %>");

app/views/spent_time/update_entry.js.erb
var flashNotice = $("#flash_notice");
flashNotice.remove();
$("#flash_error").remove();
$("#content").prepend("<div class='flash notice' id='flash_notice'><%=flash[:notice]%></div>");
$('#time_entries_report').html("<%= escape_javascript(render :partial => 'time_entries_report')%>");
flashNotice.fadeOut(3000);

app/views/spent_time/update_project_issues.js.erb
$('#fields_for_new_entry_form').html("<%= escape_javascript(render :partial => 'fields_for_new_entry_form') %>");